artifacts_root: artifacts

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "https://github.com/kishor2004reddy/Datasets/raw/refs/heads/main/WineQuality.zip"
  local_data_file: "artifacts/data_ingestion/data.zip"
  unzip_dir: "artifacts/data_ingestion"

